const projects = [
  {
    name: 'Les petits plats',
    logo: 'https://zupimages.net/up/22/40/5l10.png',
    description: 'Développez un algorithme de recherche en JavaScript',
    image: 'https://zupimages.net/up/22/35/cafy.png',
    link: 'https://giulianoloic-7-30062022-b5y53iykx-devweb13.vercel.app/',
    technologies: ['react', 'js', 'sass', 'node', 'express', 'vercel', 'jsdoc'],
    gitHub: 'https://github.com/DevWeb13/giulianoloic_7_30062022',
    date: "2022-07",
    categorie: "OpenClassrooms",
  },
  {
    name: 'Wealth Health',
    logo: 'https://zupimages.net/up/22/40/58eh.png',
    description: 'Faites passer une librairie jQuery vers React',
    image: 'https://zupimages.net/up/22/35/gqu2.png',
    link: 'https://giulianoloic-14-28052022.vercel.app/',
    technologies: ['react', 'js', 'sass', 'node', 'express', 'vercel', 'jsdoc'],
    gitHub: 'https://github.com/DevWeb13/giulianoloic_14_28052022',
    date: "2022-06",
    categorie: "OpenClassrooms",
  },
  {
    name: 'SportSee',
    logo: 'https://zupimages.net/up/22/40/gnjv.png',
    description: 'Développez un tableau de bord d\'analytics avec React',
    image: 'https://zupimages.net/up/22/35/3jsa.png',
    link: 'https://giuliano-loic-12-26022022-hnc6ozb63-devweb13.vercel.app/',
    technologies: ['react', 'js', 'sass', 'node', 'recharts', 'vercel', 'jsdoc'],
    gitHub: 'https://github.com/DevWeb13/GiulianoLoic_12_26022022',
    date: "2022-03",
    categorie: "OpenClassrooms",
  },
  {
    name: "Kasa",
    logo: 'https://zupimages.net/up/22/40/s4dt.png',
    description: "Développez une application Web avec React et React Router",
    image: "https://zupimages.net/up/22/34/5aib.png",
    link: "https://giuliano-loic-11-07022022.vercel.app/",
    technologies: ["react", "sass", "js", "vercel", 'jsdoc'],
    gitHub: "https://github.com/DevWeb13/GiulianoLoic_11_07022022",
    date: "2022-03",
    categorie: "OpenClassrooms",
  },
  {
    name: "FishEye",
    logo: 'https://zupimages.net/up/22/40/e49h.png',
    description: "Créez un site accessible pour une plateforme de photographes",
    image: "https://zupimages.net/up/22/34/ux6c.png",
    link: "https://devweb13.github.io/GiulianoLoic_6_05112021/www/",
    technologies: ["html", "css", "js", "gulp", "sass", "webpack", "accessibility"],
    gitHub: "https://github.com/DevWeb13/GiulianoLoic_6_05112021",
    date: "2022-01",
    categorie: "OpenClassrooms",
  },
  {
    name: 'Ohmyfood!',
    logo: 'https://zupimages.net/up/22/40/hm0j.png',
    description: 'Dynamisez une page web avec des animations CSS',
    image: 'https://zupimages.net/up/22/35/oba3.png',
    link: 'https://devweb13.github.io/GiulianoLoic_3_26082021/',
    technologies: ['html', 'css', 'sass'],
    gitHub: 'https://github.com/DevWeb13/GiulianoLoic_3_26082021',
    date: "2021-09",
    categorie: "OpenClassrooms",
  },
  {
    name: "Reservia",
    logo: 'https://zupimages.net/up/22/40/noz6.png',
    description: "Transformez une maquette en site web",
    image: "https://zupimages.net/up/22/35/1xvl.png",
    link: "https://devweb13.github.io/GiulianoLoic_2_11082021/",
    technologies: ["html", "css"],
    gitHub: "https://github.com/DevWeb13/GiulianoLoic_2_11082021",
    date: "2021-08",
    categorie: "OpenClassrooms",

  },
]

module.exports = projects;